packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - expo-dev-client@57.0.15
  - expo-dev-launcher@57.0.15
  - expo-dev-menu@57.0.15
